# Ghehlien

**Ghehlien** (系聯) is a clustering method used in Old Chinese Phonology

## 1. Prerequisites

### 1.1 Playing with Fuzzy Numbers

Defining a new type called `FuzzyFloat`, in which `*` becomes `min` and `+` becomes `max`.

In [1]:
include("fuzzynum.jl")
using fuzzynum

In [2]:
FuzzyFloat(0.5) + FuzzyFloat(0.6)

0.6

In [3]:
a = [FuzzyFloat(0.4) FuzzyFloat(0.8); FuzzyFloat(0.2) FuzzyFloat(0.6)]

2×2 Array{fuzzynum.FuzzyFloat,2}:
 0.4  0.8
 0.2  0.6

In [4]:
b = [FuzzyFloat(0.2) FuzzyFloat(0.7); FuzzyFloat(0.5) FuzzyFloat(0.1)]

2×2 Array{fuzzynum.FuzzyFloat,2}:
 0.2  0.7
 0.5  0.1

In [5]:
a * b

2×2 Array{fuzzynum.FuzzyFloat,2}:
 0.5  0.4
 0.5  0.2

### 1.2 Reading data from file

In [6]:
using CSV

When reading data from a CSV file, the result would be `DataFrames.DataFrame`.

In [7]:
df = CSV.read("data.csv", types = Dict(7 => String))

25333×7 DataFrames.DataFrame. Omitted printing of 3 columns
│ Row   │ 廣韻韻部順序&廣韻韻部原貌(調整前) │ 小韻序 │ 上字 │ 下字 │
├───────┼───────────────────────────────────┼────────┼──────┼──────┤
│ 1     │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 2     │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 3     │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 4     │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 5     │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 6     │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 7     │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 8     │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 9     │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 10    │ 上平01東                          │ 1      │ 德   │ 紅   │
│ 11    │ 上平01東                          │ 1      │ 德   │ 紅   │
⋮
│ 25322 │ 下平01先                          │ 576    │ 昨   │ 先   │
│ 25323 │ 下平09麻                          │ 777    │ 女   │ 加   │
│ 25324 │ 下平17登                          │ 974    │ 武   │ 登   │
│ 25325 │ 下平27銜                          │ 1148   │ 古   │ 銜   │
│ 25326 │ 上14賄                            │ 1441   │ 七   │ 罪   │
│ 25327 │ 去06至                            │ 2230   │ 息   │ 利   │
│ 25328 │ 去31襇                            │ 2687   │ 蒲   │ 莧   │
│ 25329 │ 去42宕                            │ 2936   │ 他   │ 浪   │
│ 25330 │ 去54闞                            │ 3121   │ 古   │ 蹔   │
│ 25331 │ 入11沒                            │ 3390   │ 戶   │ 骨   │
│ 25332 │ 入16屑                            │ 3473   │ 古   │ 穴   │
│ 25333 │ 入29葉                            │ 3817   │ 尼   │ 輒   │

In [8]:
mapfoldl(length, +, 0, df[5])/25333  # Process the column 中古拼音(polyhedron 版)

4.192949907235621

## 2. Analyses of Kuangxyonh

In this section, the ghehlien of **pyanxchet upper characters** (反切上字) and **pyanxchet lower characters** (反切下字) in **Kuangxyonh** (廣韻) will be analysed.

### 2.1 Pyanxchet Upper Characters

**2.1.1. Create a new set $S$ and put all upper characters into it:**

In [9]:
s = Set(df[:上字])

Set(Union{CategoricalArrays.CategoricalString{UInt32}, Missings.Missing}[CategoricalArrays.CategoricalString{UInt32} "當", CategoricalArrays.CategoricalString{UInt32} "跪", CategoricalArrays.CategoricalString{UInt32} "女", CategoricalArrays.CategoricalString{UInt32} "握", CategoricalArrays.CategoricalString{UInt32} "羽", CategoricalArrays.CategoricalString{UInt32} "危", CategoricalArrays.CategoricalString{UInt32} "尼", CategoricalArrays.CategoricalString{UInt32} "羊", CategoricalArrays.CategoricalString{UInt32} "同", CategoricalArrays.CategoricalString{UInt32} "醋"  …  CategoricalArrays.CategoricalString{UInt32} "匹", CategoricalArrays.CategoricalString{UInt32} "連", CategoricalArrays.CategoricalString{UInt32} "征", CategoricalArrays.CategoricalString{UInt32} "并", CategoricalArrays.CategoricalString{UInt32} "下", CategoricalArrays.CategoricalString{UInt32} "辝", CategoricalArrays.CategoricalString{UInt32} "色", CategoricalArrays.CategoricalString{UInt32} "卑", CategoricalArrays.CategoricalString{UInt32

In [10]:
filter!(x -> typeof(x) != Missings.Missing, s)  # Remove missing data, for those small rhymes (小韻) that has no pyanxchet

Set(Union{CategoricalArrays.CategoricalString{UInt32}, Missings.Missing}[CategoricalArrays.CategoricalString{UInt32} "當", CategoricalArrays.CategoricalString{UInt32} "跪", CategoricalArrays.CategoricalString{UInt32} "女", CategoricalArrays.CategoricalString{UInt32} "握", CategoricalArrays.CategoricalString{UInt32} "羽", CategoricalArrays.CategoricalString{UInt32} "危", CategoricalArrays.CategoricalString{UInt32} "尼", CategoricalArrays.CategoricalString{UInt32} "羊", CategoricalArrays.CategoricalString{UInt32} "同", CategoricalArrays.CategoricalString{UInt32} "醋"  …  CategoricalArrays.CategoricalString{UInt32} "匹", CategoricalArrays.CategoricalString{UInt32} "連", CategoricalArrays.CategoricalString{UInt32} "征", CategoricalArrays.CategoricalString{UInt32} "并", CategoricalArrays.CategoricalString{UInt32} "下", CategoricalArrays.CategoricalString{UInt32} "辝", CategoricalArrays.CategoricalString{UInt32} "色", CategoricalArrays.CategoricalString{UInt32} "卑", CategoricalArrays.CategoricalString{UInt32

**2.1.2. Get the length of the set $S$, construct an empty $n*n$ array**

In [11]:
n = length(s)

471

In [12]:
arr = zeros(Int, n, n)

471×471 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  

**2.1.3. Generate a list $xs$ from set $S$**

In [13]:
function setToList(s)
    dupS = copy(s)
    n = length(dupS)
    xs = []
    for i in 1:n
        push!(xs, pop!(dupS))
    end
    xs
end

setToList (generic function with 1 method)

In [14]:
xs = setToList(s)

471-element Array{Any,1}:
 "兹"
 "鋤"
 "爭"
 "明"
 "之"
 "數"
 "北"
 "彼"
 "衢"
 "爲"
 "匹"
 "愛"
 "傍"
 ⋮  
 "平"
 "區"
 "速"
 "始"
 "呵"
 "部"
 "諸"
 "丕"
 "榮"
 "遵"
 "除"
 "狂"

**2.1.4. Set `count` = 0**

In [15]:
count = 0

0

**2.1.5. Iterate `xs`, for all `x` in `xs`, find the upper character of `x`**

**Then, let $i_1$ be the index of `x` in `xs`, $i_2$ be the index of (the upper character of `x`) in `xs`**

**Increace one for array $(i_1, i_2)$ and $(i_2, i_1)$**

In [16]:
function findUpperChar(ch)
    for (wrd, ucOfWrd) in zip(df[6], df[:上字])
        if wrd == ch
            return ucOfWrd
        end
    end
end

findUpperChar (generic function with 1 method)

In [17]:
function getUpperCharIndex(ch :: typeof(xs[1]))
    for i in 1:n
        if ch == xs[i]
            return i
        end
    end
end

getUpperCharIndex (generic function with 1 method)

In [18]:
getUpperCharIndex(findUpperChar(df[6][1]))

33

In [19]:
for i in 1:n
    i1 = i
    i2 = getUpperCharIndex(findUpperChar(xs[i]))
    arr[i1, i2] += 1
    arr[i2, i1] += 1
end

**2.1.6. Get the transitive closure of `arr`**

In [20]:
FuzzyArr = map(x -> FuzzyFloat(x / n), arr)

471×471 Array{fuzzynum.FuzzyFloat,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  

In [21]:
function getTransitiveClosure(FuzzyArr)
    while true
        arr_new = FuzzyArr * FuzzyArr
        if arr_new == FuzzyArr
            return arr_new
        end
        FuzzyArr = arr_new
    end
end       

getTransitiveClosure (generic function with 1 method)

In [22]:
FuzzyArr_TC = getTransitiveClosure(FuzzyArr)

471×471 Array{fuzzynum.FuzzyFloat,2}:
 0.00212314  0.0         0.0         …  0.0         0.0         0.0       
 0.0         0.00212314  0.0            0.0         0.0         0.0       
 0.0         0.0         0.00212314     0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0         …  0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0         …  0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0       

In [23]:
Set(map(x -> Float64(x), FuzzyArr_TC))

Set([0.00212314, 0.00424628, 0.0])

In [24]:
FuzzyArr_Regression_TC = getTransitiveClosure(map(x -> FuzzyFloat(x == zero(x) ? 0.0 : 1.0), FuzzyArr))

471×471 Array{fuzzynum.FuzzyFloat,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  

In [25]:
function getCluster(arr)
    arr_new = map(x -> Float64(x), arr)

    ss = []
    for i in 1:n
        if all(xs -> !in(i, xs), ss)
            s = map(x -> x[2], filter(x -> x[1] != zero(x[1]), zip(view(arr_new, :, i), collect(1:n))))
            if length(s) != 0
                push!(ss, s)
            end
        end
    end
    ss
end

getCluster (generic function with 1 method)

In [26]:
c_regress = getCluster(FuzzyArr_Regression_TC)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] filter(::Function, ::Base.Iterators.Zip2{SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},Array{Int64,1}}) at .\deprecated.jl:57
 [3] getCluster(::Array{fuzzynum.FuzzyFloat,2}) at .\In[25]:7
 [4] include_string(::String, ::String) at .\loading.jl:522
 [5] include_string(::Module, ::String, ::String) at E:\julia-depot\v0.6\Compat\src\Compat.jl:88
 [6] execute_request(::ZMQ.Socket, ::IJulia.Msg) at E:\julia-depot\v0.6\IJulia\src\execute_request.jl:180
 [7] (::Compat.#inner#14{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at E:\julia-depot\v0.6\Compat\src\Compat.jl:332
 [8] eventloop(::ZMQ.Socket) at E:\julia-depot\v0.6\IJulia\src\eventloop.jl:8
 [9] (::IJulia.##15#18)() at .\task.jl:335
while loading In[26], in expression starting on line 1


88-element Array{Any,1}:
 [1, 30, 203, 222, 263, 421, 443]                                         
 [2, 74, 84, 118, 158, 360, 391, 397]                                     
 [3, 134, 230, 380, 438]                                                  
 [4, 17, 41, 48, 52, 90, 119, 258, 285, 298, 366, 426]                    
 [5, 83, 86, 243, 289, 335, 408, 466]                                     
 [6, 71, 115, 133, 138, 233, 244, 305]                                    
 [7, 40, 79, 320, 388, 407]                                               
 [8, 63, 65, 68, 82, 98, 177, 192, 193, 268, 347, 352, 355, 427, 436, 454]
 [9, 80, 319, 329, 435]                                                   
 [10, 95, 266, 280, 359, 468]                                             
 [11]                                                                     
 [12, 23, 145, 162]                                                       
 [13, 127, 146, 198, 317, 433]                                            


In [27]:
for i in map(m -> join(map(n -> xs[n], m)), c_regress)
    println(i)
end

兹匠疾自情慈秦
鋤鶵查豺雛崱鉏牀
爭阻莊鄒簪
明靡文美武亡望眉巫彌綿無
之氏占旨煑識支諸
數山沙色疏疎生砂
北伯布補百晡
彼兵并防筆婢卑方皮縛畀分裴封附房
衢具渠臼巨
爲于有韋王榮
匹
愛哀安鷖
傍白捕薄蒲步
先胥須息素寫速
雨筠羽薳洧雲云永
胡侯乎懷
父甫必弼陂符扶毗馮浮府鄙便平部
弋台隨悅實營辝余似旬夷辭以羊乘食寺詳移翼徐祥予與餘神夕
堂唐特同陀度杜
憂謁握央依烟委衣一乙伊憶
驅傾跪袪乞丘欽詰羌卿窺墟區
側仄
博邊巴
獲下戶何黃
署是視市寔殖
德得
嘗承成常蜀殊時
力良離
借𩛠醉作即姊漸則遵
當冬
仕崇助士
廁創瘡初叉楚測芻
連縷里呂林
郎
章征止脂職正
治丈持佇植遟墜池場柱馳除
天吐土託通
蘇司辛雖斯桑思相私悉
虛香羲朽休興況許喜
姑乖各過兼楷公佳格
母模慕摸謨
洛勒落
如儒耳汝
火虎花馨荒海
宅臣直
豬追張竹丁卓徵陟珍迍知中褚猪
蒼取倉遷親
牛俄虞魚疑研愚吾
乃內諾㚷
康口謙枯恪空牽客
女
強俟求暨奇其狂
披拂芳峯丕
弃起曲綺去豈
前藏在徂才
挹於紆
徒
舉規居九俱紀几吉
資祖將子臧
敷孚撫妃
式釋書舒始
矢施詩試傷失湯賞商
麁采麤醋青七千
抽楮癡敕
滂
充處赤尺叱
拏尼穠
都
烏
兒人而仍
雌
危宜玉遇擬五語
奴那
莫
恥丑
古詭
魯練
苦可
所史
普
此
賴盧來
他
譬
多
呼呵
昌
昨


### 2.2 Pyanxchet Lower Characters

**2.2.1. Create a new set $S$ and put all upper characters into it:**

In [28]:
s = Set(df[:下字])

Set(Union{CategoricalArrays.CategoricalString{UInt32}, Missings.Missing}[CategoricalArrays.CategoricalString{UInt32} "懈", CategoricalArrays.CategoricalString{UInt32} "甾", CategoricalArrays.CategoricalString{UInt32} "當", CategoricalArrays.CategoricalString{UInt32} "甚", CategoricalArrays.CategoricalString{UInt32} "法", CategoricalArrays.CategoricalString{UInt32} "賄", CategoricalArrays.CategoricalString{UInt32} "越", CategoricalArrays.CategoricalString{UInt32} "俾", CategoricalArrays.CategoricalString{UInt32} "運", CategoricalArrays.CategoricalString{UInt32} "河"  …  CategoricalArrays.CategoricalString{UInt32} "亞", CategoricalArrays.CategoricalString{UInt32} "寸", CategoricalArrays.CategoricalString{UInt32} "教", CategoricalArrays.CategoricalString{UInt32} "戀", CategoricalArrays.CategoricalString{UInt32} "畏", CategoricalArrays.CategoricalString{UInt32} "位", CategoricalArrays.CategoricalString{UInt32} "鄭", CategoricalArrays.CategoricalString{UInt32} "醒", CategoricalArrays.CategoricalString{UInt32

In [29]:
filter!(x -> typeof(x) != Missings.Missing, s)  # Remove missing data, for those small rhymes (小韻) that has no pyanxchet

Set(Union{CategoricalArrays.CategoricalString{UInt32}, Missings.Missing}[CategoricalArrays.CategoricalString{UInt32} "懈", CategoricalArrays.CategoricalString{UInt32} "甾", CategoricalArrays.CategoricalString{UInt32} "當", CategoricalArrays.CategoricalString{UInt32} "甚", CategoricalArrays.CategoricalString{UInt32} "法", CategoricalArrays.CategoricalString{UInt32} "賄", CategoricalArrays.CategoricalString{UInt32} "越", CategoricalArrays.CategoricalString{UInt32} "俾", CategoricalArrays.CategoricalString{UInt32} "運", CategoricalArrays.CategoricalString{UInt32} "河"  …  CategoricalArrays.CategoricalString{UInt32} "亞", CategoricalArrays.CategoricalString{UInt32} "寸", CategoricalArrays.CategoricalString{UInt32} "教", CategoricalArrays.CategoricalString{UInt32} "戀", CategoricalArrays.CategoricalString{UInt32} "畏", CategoricalArrays.CategoricalString{UInt32} "位", CategoricalArrays.CategoricalString{UInt32} "鄭", CategoricalArrays.CategoricalString{UInt32} "醒", CategoricalArrays.CategoricalString{UInt32

**2.2.2. Get the length of the set $S$, construct an empty $n*n$ array**

In [30]:
n = length(s)

1187

In [31]:
arr = zeros(Int, n, n)

1187×1187 Array{Int64,2}:
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0  …  0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0     0  0  0  0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0  0  0  0  0

**2.2.3. Generate a list $xs$ from set $S$**

In [32]:
# function setToList(s)

In [33]:
xs = setToList(s)

1187-element Array{Any,1}:
 "婁"
 "肌"
 "焉"
 "肴"
 "制"
 "懈"
 "鍾"
 "預"
 "孟"
 "綸"
 "爲"
 "灼"
 "甾"
 ⋮  
 "杯"
 "佃"
 "贈"
 "襃"
 "拜"
 "荏"
 "允"
 "赧"
 "牒"
 "斗"
 "曹"
 "圓"

**2.2.4. Set `count` = 0**

In [34]:
count = 0

0

**2.2.5. Iterate `xs`, for all `x` in `xs`, find the upper character of `x`**

**Then, let $i_1$ be the index of `x` in `xs`, $i_2$ be the index of (the upper character of `x`) in `xs`**

**Increace one for array $(i_1, i_2)$ and $(i_2, i_1)$**

In [35]:
function findLowerChar(ch)
    for (wrd, ucOfWrd) in zip(df[6], df[:下字])
        if wrd == ch
            return ucOfWrd
        end
    end
end

findLowerChar (generic function with 1 method)

In [36]:
function getLowerCharIndex(ch :: typeof(xs[1]))
    for i in 1:n
        if ch == xs[i]
            return i
        end
    end
end

getLowerCharIndex (generic function with 1 method)

In [37]:
getLowerCharIndex(findLowerChar(df[6][1]))

595

In [38]:
for i in 1:n
    if typeof(findLowerChar(xs[i])) != typeof(findLowerChar(xs[1]))
        @show i, typeof(findLowerChar(xs[i]))
    end
end

(i, typeof(findLowerChar(xs[i]))) = (278, Void)
(i, typeof(findLowerChar(xs[i]))) = (816, Missings.Missing)


In [39]:
for i in 1:n
    i1 = i
    lc = findLowerChar(xs[i])
    if typeof(findLowerChar(xs[i])) == typeof(findLowerChar(xs[1]))
        i2 = getLowerCharIndex(lc)
        arr[i1, i2] += 1
        arr[i2, i1] += 1
    end
end

**6. Get the transitive closure of `arr`**

In [40]:
FuzzyArr = map(x -> FuzzyFloat(x / n), arr)

1187×1187 Array{fuzzynum.FuzzyFloat,2}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [41]:
# function getTransitiveClosure(FuzzyArr) 

In [42]:
FuzzyArr_TC = getTransitiveClosure(FuzzyArr)

1187×1187 Array{fuzzynum.FuzzyFloat,2}:
 0.00084246  0.0         0.0         …  0.0         0.0         0.0       
 0.0         0.00084246  0.0            0.0         0.0         0.0       
 0.0         0.0         0.00084246     0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0         …  0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0         …  0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0         0.0       
 0.0         0.0         0.0            0.0         0.0     

In [43]:
Set(map(x -> Float64(x), FuzzyArr_TC))

Set([0.00168492, 0.00084246, 0.0])

In [44]:
FuzzyArr_Regression_TC = getTransitiveClosure(map(x -> FuzzyFloat(x == zero(x) ? 0.0 : 1.0), FuzzyArr))

1187×1187 Array{fuzzynum.FuzzyFloat,2}:
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0     0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [45]:
function getCluster(arr)
    arr_new = map(x -> Float64(x), arr)

    ss = []
    for i in 1:n
        if all(xs -> !in(i, xs), ss)
            s = map(x -> x[2], filter(x -> x[1] != zero(x[1]), zip(view(arr_new, :, i), collect(1:n))))
            if length(s) != 0
                push!(ss, s)
            end
        end
    end
    ss
end

getCluster (generic function with 1 method)

In [46]:
c_regress = getCluster(FuzzyArr_Regression_TC)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at .\deprecated.jl:70
 [2] filter(::Function, ::Base.Iterators.Zip2{SubArray{Float64,1,Array{Float64,2},Tuple{Base.Slice{Base.OneTo{Int64}},Int64},true},Array{Int64,1}}) at .\deprecated.jl:57
 [3] getCluster(::Array{fuzzynum.FuzzyFloat,2}) at .\In[45]:7
 [4] include_string(::String, ::String) at .\loading.jl:522
 [5] include_string(::Module, ::String, ::String) at E:\julia-depot\v0.6\Compat\src\Compat.jl:88
 [6] execute_request(::ZMQ.Socket, ::IJulia.Msg) at E:\julia-depot\v0.6\IJulia\src\execute_request.jl:180
 [7] (::Compat.#inner#14{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at E:\julia-depot\v0.6\Compat\src\Compat.jl:332
 [8] eventloop(::ZMQ.Socket) at E:\julia-depot\v0.6\IJulia\src\eventloop.jl:8
 [9] (::IJulia.##15#18)() at .\task.jl:335
while loading In[46], in expression starting on line 1


495-element Array{Any,1}:
 [1, 83, 320, 379, 476, 573, 829, 1001, 1008, 1112, 1155]                    
 [2, 168, 266, 394, 552, 803, 909]                                           
 [3, 439]                                                                    
 [4, 35, 160, 230, 388, 418, 801, 1060, 1128]                                
 [5, 203, 213, 789, 943, 985]                                                
 [6, 862]                                                                    
 [7, 279, 356, 384, 984]                                                     
 [8, 93, 101, 117, 136, 153, 302, 303, 515, 518, 892, 952, 1021, 1048]       
 [9, 25, 30, 287, 664, 716, 775]                                             
 [10, 26, 336, 414]                                                          
 [11, 43, 55, 70, 147, 296, 405, 498, 502, 554, 583, 603, 812, 852, 860, 882]
 [12, 13, 61, 177, 198, 314, 542, 568, 780, 782, 854, 902, 905, 989]         
 [14]                                 

In [47]:
for i in map(m -> join(map(n -> xs[n], m)), c_regress)
    println(i)
end

婁熱足別滅輸俞辥逾俱芻
肌尼糾資私脂飢
焉軒
肴孝交嘲茅稍皃覺教
制訐罽袂憩祭
懈卦
鍾封用凶恭
預遮若嗟居車藥諸其而兹略野持
孟行當盲宕剛岡
綸筠倫旬
爲倚毀吹帋紙規離移累詭彼此髓爾侈
灼甾姐魚奢邪爵洳雀賒與之勺余
隱
焮
帶太大轄貝艾
敢
合閤荅沓雜
彪幽
類醉
賜避昔智寄亦辟豉
佞徑
哀
勞遭牢
冉廉淹染
政正成盛盈貞姓征并情鄭
貢弄鳳送
晏按案贊
妙約
幸
蛙
鑒
文倦員變云戀圓
綏追
記既溉志置
隨危垂是綺知支靡捶氏隋委豸
道抱老早
甚深淫朕
法
贍
乎胡都
姑吾孤烏吳
皛晈鳥皎
賄
典
激嘯叫
妹昧
酉有柳婦
麵見練
夥買
幻幰蹇免
摘核責厄戹
越八發
戶補魯杜
俾婢企弭
或
男𧸖南韽
刮
筆
涬冷靈刑萌莖迥挺醒
巷
界戒怪壞介拜
逼力
灰回
恕
證升𩜁仍甑陵
于朱句列誅隅
運
勒德得
昆
計
緣
四質叱至寐畢必自一冀七
靳
唾縛貨
朗
犯范
河何俄歌
令然連
店
六
㢡掌网妄養丈往
疋
恆滕棱朋
賀佐
訪亮向況讓㨾
維遺隹
候
羽甫雨禹
展煙先淺善
真振珍遴印晉人賓
輩佩
𩏩
𠁥蟹
飽絞
割曷葛達
還鰥
月物勿
銜
牙霞巴
敏
泛中戎仲
蒸乘應庱矜冰膺孕兢
豔
禾婆和
但寒
兼
檻濫感
里史理擬
墨黑
張章莊
輒接涉
丸潘喚端筭
夷黝
奏漏豆遘
董摠
華瓜花
話夬
玉欲蜀曲錄
逐菊竹福匊
巧爪
在等亥
膎
哉
戰
冬
任心尋
即側極直
郤逆戟劇
尾
后厚斗
恩根
霸㕦訝亞
羊陽良
楷皆
遇注
爇歲芮輟
公蠓空東凍
扃
駭諧
䒦
乙密
演翦輦前
緩伴滿纂笴
葉攝
拔伐黠
崩增登
瀌夭表嬌矯喬囂
滑結骨
內報隊繢
川泉全宣專
甲
脣贇遵勻迍
閑山
謝炙
呪宿祐副溜又
殞
板
仙扇延
偃辨堰
協
京驚
甜
病
冢奉踵宂勇
覽埯
役石
䫄
奇宜
末
桂
广奄險
林
翼
篆轉緬
迄乞
綜宋統
庾
尊䰟渾奔
潁營䁝
昭招
紀士己
湩
準
擊狄
建阮怨販煩晚元
秋周求州
外
臘榼
會最
黃旁
水誄鄙壘洧
漸炎琰占斂鹽
𣊟暫唵瞰禫蹔黤
郭格各
浮
玄縣
卹聿律
益迹積義恚易
靜整井
鎋
淮懷
權彥囀攣眷分卷
凡
革
葅
三酣談
悚
臡奚兮
路誤暮
勃
礦杏
劫業
味未
邏个箇
蔭凜吟鴆
懺
降雙
北
嫁駕化
虐笑肖
耐愛概
謬
管旱
戢急及汲㘝入
峴殄繭
博落穫
慣
影永
紺
年賢
美軌癸否
橫光
緺媧
弔
禮
陌虢
就
瓦
尤由鳩流
澗鴈旰諫旦
錽
代
火
羈
篤沃